#!/usr/bin/env php
<?php

/*
 * Laravel Artisan CLI
 * Digunakan untuk menjalankan command seperti php artisan serve, migrate, dll
 */

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(\Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(
    $input = new \Symfony\Component\Console\Input\ArgvInput,
    new \Symfony\Component\Console\Output\ConsoleOutput
));
